# =============================================
# ============== O M N I P O O L ==============
# =============================================

manifestVersion: subsquid.io/v0.1
name: hydration-storage-dictionary
slot: 302
description: Hydration storage dictionary for Omnipool storage
build:
deploy:
  addons:
    postgres:
      config:
        statement_timeout: 360000
        log_min_duration_statement: 60000
  processor:
    - name: omnipool-batch-proc-1
      cmd: ['sqd', 'process:prod']
      env:
        RPC_HYDRATION_URL: wss://archive.rpc.hydration.cloud
        GATEWAY_HYDRATION_HTTPS: https://v2.archive.subsquid.io/network/hydradx
        PROCESS_LBP_POOLS: false
        PROCESS_XYK_POOLS: false
        PROCESS_OMNIPOOLS: true
        PROCESS_STABLEPOOLS: false
        GQL_PORT: 8080
        NODE_ENV: production
        OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
        START_BLOCK: 1708100
        END_BLOCK: 2500000
        STATE_SCHEMA_NAME: omnipool__batch_proc_1
    - name: omnipool-batch-proc-2
      cmd: ['sqd', 'process:prod']
      env:
        RPC_HYDRATION_URL: wss://archive.rpc.hydration.cloud
        GATEWAY_HYDRATION_HTTPS: https://v2.archive.subsquid.io/network/hydradx
        PROCESS_LBP_POOLS: false
        PROCESS_XYK_POOLS: false
        PROCESS_OMNIPOOLS: true
        PROCESS_STABLEPOOLS: false
        GQL_PORT: 8080
        NODE_ENV: production
        OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
        START_BLOCK: 2500001
        END_BLOCK: 3300000
        STATE_SCHEMA_NAME: omnipool__batch_proc_2
    - name: omnipool-batch-proc-3
      cmd: ['sqd', 'process:prod']
      env:
        RPC_HYDRATION_URL: wss://archive.rpc.hydration.cloud
        GATEWAY_HYDRATION_HTTPS: https://v2.archive.subsquid.io/network/hydradx
        PROCESS_LBP_POOLS: false
        PROCESS_XYK_POOLS: false
        PROCESS_OMNIPOOLS: true
        PROCESS_STABLEPOOLS: false
        GQL_PORT: 8080
        NODE_ENV: production
        OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
        START_BLOCK: 3300001
        END_BLOCK: 4100000
        STATE_SCHEMA_NAME: omnipool__batch_proc_3
    - name: omnipool-batch-proc-4
      cmd: ['sqd', 'process:prod']
      env:
        RPC_HYDRATION_URL: wss://archive.rpc.hydration.cloud
        GATEWAY_HYDRATION_HTTPS: https://v2.archive.subsquid.io/network/hydradx
        PROCESS_LBP_POOLS: false
        PROCESS_XYK_POOLS: false
        PROCESS_OMNIPOOLS: true
        PROCESS_STABLEPOOLS: false
        GQL_PORT: 8080
        NODE_ENV: production
        OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
        START_BLOCK: 4100001
        END_BLOCK: -1
        STATE_SCHEMA_NAME: omnipool__batch_proc_4
    - name: omnipool-batch-proc-5
      cmd: ['sqd', 'process:prod']
      env:
        RPC_HYDRATION_URL: wss://archive.rpc.hydration.cloud
        GATEWAY_HYDRATION_HTTPS: https://v2.archive.subsquid.io/network/hydradx
        PROCESS_LBP_POOLS: false
        PROCESS_XYK_POOLS: false
        PROCESS_OMNIPOOLS: true
        PROCESS_STABLEPOOLS: false
        GQL_PORT: 8080
        NODE_ENV: production
        OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
        START_BLOCK: 4000001
        END_BLOCK: -1
        STATE_SCHEMA_NAME: omnipool__batch_proc_5
  api:
    env:
      RPC_HYDRATION_URL: wss://archive.rpc.hydration.cloud
      GATEWAY_HYDRATION_HTTPS: https://v2.archive.subsquid.io/network/hydradx
      PROCESS_LBP_POOLS: false
      PROCESS_XYK_POOLS: false
      PROCESS_OMNIPOOLS: true
      PROCESS_STABLEPOOLS: false
      GQL_PORT: 8080
      NODE_ENV: production
      OMNIPOOL_ADDRESS: '0x6d6f646c6f6d6e69706f6f6c0000000000000000000000000000000000000000'
      ALL_STATE_SCHEMAS_LIST: 'omnipool__batch_proc_1,omnipool__batch_proc_2,omnipool__batch_proc_3,omnipool__batch_proc_4,omnipool__batch_proc_5'
    cmd:
      - sqd
      - api:prod
scale:
  dedicated: false
  addons:
    postgres:
      profile: large
      storage: 60G
  processor:
    profile: large
