export * as system from './system/storage'
export * as tokens from './tokens/storage'
export * as omnipool from './omnipool/storage'
export * as lbp from './lbp/storage'
export * as stableswap from './stableswap/storage'
export * as xyk from './xyk/storage'
